apiVersion: v1
kind: Service
metadata:
  name: altkom-account
spec:
  type: NodePort
  selector:
    app: altkom-account
  ports:
    - name: http
      nodePort: 30000
      port: 8080
      protocol: TCP
      targetPort: 8080